Import('env')

sources = [
	'action_store.cpp',
	'lex_util.cpp',
	'node_set.cpp',
	'tinystr.cpp',
	'tinyxml.cpp',
	'tinyxmlerror.cpp',
	'tinyxmlparser.cpp',
	'tokenlist.cpp',
	'xml_util.cpp',
	'xpath_expression.cpp',
	'xpath_processor.cpp',
	'xpath_stack.cpp',
	'xpath_static.cpp',
	'xpath_stream.cpp',
	'xpath_syntax.cpp' ]

obj = env.Object ( sources )

Return ( 'obj' )
